{"uuid":"e8ebbe66-91c0-41b1-8c57-d7ce671dfcb6","historyId":"857a44c17d54cd4d79ba8a1011bc6962","testCaseId":"[engine:junit-jupiter]/[class:uitests.tasks.AddNewDeratizationTaskTest]","testCaseName":"AddNewDeratizationTaskTest","fullName":"uitests.tasks.AddNewDeratizationTaskTest","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:uitests.tasks.AddNewDeratizationTaskTest]"},{"name":"host","value":"WIN-3RAHDNDFC19"},{"name":"thread","value":"33592@WIN-3RAHDNDFC19.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"uitests.tasks.AddNewDeratizationTaskTest"},{"name":"testClass","value":"uitests.tasks.AddNewDeratizationTaskTest"},{"name":"suite","value":"uitests.tasks.AddNewDeratizationTaskTest"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"AddNewDeratizationTaskTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Ошибка при выполнении запроса","trace":"java.lang.RuntimeException: Ошибка при выполнении запроса\r\n\tat services.database.DBService.values(DBService.java:68)\r\n\tat builders.TaskBuilder.setEnterpriseName(TaskBuilder.java:166)\r\n\tat factory.TaskFactory.createTask(TaskFactory.java:17)\r\n\tat uitests.tasks.AddNewDeratizationTaskTest.setUpAll(AddNewDeratizationTaskTest.java:45)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat io.qameta.allure.junit5.AllureJunit5.processFixture(AllureJunit5.java:138)\r\n\tat io.qameta.allure.junit5.AllureJunit5.interceptBeforeAllMethod(AllureJunit5.java:100)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\nCaused by: java.sql.SQLSyntaxErrorException: (conn=55134) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLAND enterprises.id NOT IN ( SELECT task_enterprises.enterprise_id \r\n\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)\r\n\tat org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)\r\n\tat org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)\r\n\tat org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)\r\n\tat org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:502)\r\n\tat services.database.DBService.values(DBService.java:63)\r\n\t... 7 more\r\nCaused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULLAND enterprises.id NOT IN ( SELECT task_enterprises.enterprise_id \nFROM t...' at line 8\nQuery is: SELECT DISTINCT enterprises.name \nFROM enterprises \nJOIN service_areas ON service_areas.id = enterprises.service_area_id\nJOIN animals ON animals.enterprise_id = enterprises.id \nJOIN users ON enterprises.user_id = users.id \nWHERE enterprises.name IS NOT NULL \nAND users.email = 'kam@kam.kam' \nAND enterprises.deleted_at IS NULLAND enterprises.id NOT IN ( SELECT task_enterprises.enterprise_id \nFROM tasks \nJOIN task_enterprises  \nON tasks.id = task_enterprises.task_id \nJOIN regagro_3_0_handbooks.epizootology_events \nON tasks.event_id = regagro_3_0_handbooks.epizootology_events.id \nJOIN inventories ON inventories.task_id = tasks.id \nWHERE regagro_3_0_handbooks.epizootology_events.name = 'Дератизация' \nAND (inventories.status_id IN (1, 4) OR tasks.date_to >= CURRENT_DATE()) UNION \nSELECT deratizations.enterprise_id \nFROM deratizations \nWHERE deratizations.next_date > CURRENT_DATE() \n)\r\n\tat org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113)\r\n\tat org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:162)\r\n\tat org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:326)\r\n\t... 9 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1729695089567,"stop":1729695089568}